// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
// @dart = 2.12
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, typeOf;
import 'package:jufa/models/models.dart' as x0 show Trip, TripUser;
import 'package:jufa/modules/supply/supply_models.dart' as x1 show Article, ArticleList, Recipe, ShoppingList;

// ignore_for_file: invalid_language_version_override
// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix1;
import 'package:jufa/layout/elements/elements.dart' as prefix9;
import 'package:jufa/layout/module/module.dart' as prefix0;
import 'package:jufa/models/models.dart' as prefix2;
import 'package:jufa/modules/profile/profile_module.dart' as prefix5;
import 'package:jufa/modules/supply/supply_models.dart' as prefix8;
import 'package:jufa/modules/supply/supply_module.dart' as prefix6;
import 'package:jufa/modules/thebutton/thebutton_module.dart' as prefix3;
import 'package:jufa/modules/users/users_module.dart' as prefix7;
import 'package:jufa/modules/welcome/welcome_module.dart' as prefix4;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.ModuleWidgetReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'ModuleElement',
            r'module.ModuleElement',
            519,
            0,
            const prefix0.ModuleWidgetReflectable(),
            const <int>[],
            const <int>[],
            const <int>[],
            -1,
            {},
            {},
            {},
            -1,
            0,
            const <int>[],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'ContentSegment',
            r'elements.ContentSegment',
            7,
            1,
            const prefix0.ModuleWidgetReflectable(),
            const <int>[],
            const <int>[],
            const <int>[],
            0,
            {},
            {},
            {},
            -1,
            1,
            const <int>[],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'HeaderSegment',
            r'elements.HeaderSegment',
            7,
            2,
            const prefix0.ModuleWidgetReflectable(),
            const <int>[],
            const <int>[],
            const <int>[],
            0,
            {},
            {},
            {},
            -1,
            2,
            const <int>[],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'QuickAction',
            r'elements.QuickAction',
            7,
            3,
            const prefix0.ModuleWidgetReflectable(),
            const <int>[],
            const <int>[],
            const <int>[],
            0,
            {},
            {},
            {},
            -1,
            3,
            const <int>[],
            null,
            null)
      ],
      <m.DeclarationMirror>[],
      <m.ParameterMirror>[],
      <Type>[prefix0.ModuleElement, prefix9.ContentSegment, prefix9.HeaderSegment, prefix9.QuickAction],
      4,
      {},
      {},
      null,
      []),
  const prefix1.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Trip',
            r'models.Trip',
            7,
            0,
            const prefix1.JsonSerializable(),
            const <int>[0, 1, 2, 3, 23, 24],
            const <int>[25, 26, 27, 28, 29, 15, 16, 17, 18, 19, 20, 21, 22, 23],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (id, name, users, modules) => b ? prefix2.Trip(id, name, users, modules) : null},
            -1,
            0,
            const <int>[],
            const [prefix1.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'TripUser',
            r'models.TripUser',
            7,
            1,
            const prefix1.JsonSerializable(),
            const <int>[4, 5, 34],
            const <int>[25, 26, 27, 28, 29, 30, 31, 32, 33],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (role, nickname) => b ? prefix2.TripUser(role, nickname) : null},
            -1,
            1,
            const <int>[],
            const [prefix1.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'Article',
            r'.Article',
            7,
            2,
            const prefix1.JsonSerializable(),
            const <int>[6, 7, 8, 9, 43],
            const <int>[25, 26, 27, 28, 29, 35, 36, 37, 38, 39, 40, 41, 42],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (id, name, category, hint) => b ? prefix8.Article(id, name, category, hint) : null},
            -1,
            2,
            const <int>[],
            const [prefix1.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'ArticleList',
            r'.ArticleList',
            7,
            3,
            const prefix1.JsonSerializable(),
            const <int>[10, 11, 12, 13, 52],
            const <int>[25, 26, 27, 28, 29, 44, 45, 46, 47, 48, 49, 50, 51],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (id, name, entries, note) => b ? prefix8.ArticleList(id, name, entries, note) : null},
            -1,
            3,
            const <int>[],
            const [prefix1.jsonSerializable, const prefix1.Json(discriminatorProperty: "type")],
            null),
        r.NonGenericClassMirrorImpl(
            r'Recipe',
            r'.Recipe',
            7,
            4,
            const prefix1.JsonSerializable(),
            const <int>[14, 55],
            const <int>[25, 26, 27, 28, 29, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54],
            const <int>[],
            3,
            {},
            {},
            {
              r'': (bool b) => (id, name, entries, preparation, note) =>
                  b ? prefix8.Recipe(id, name, entries, preparation, note) : null
            },
            -1,
            4,
            const <int>[],
            const [prefix1.jsonSerializable, const prefix1.Json(discriminatorValue: "recipe")],
            null),
        r.NonGenericClassMirrorImpl(
            r'ShoppingList',
            r'.ShoppingList',
            7,
            5,
            const prefix1.JsonSerializable(),
            const <int>[56],
            const <int>[25, 26, 27, 28, 29, 44, 45, 46, 47, 48, 49, 50, 51],
            const <int>[],
            3,
            {},
            {},
            {r'': (bool b) => (id, name, entries, note) => b ? prefix8.ShoppingList(id, name, entries, note) : null},
            -1,
            5,
            const <int>[],
            const [prefix1.jsonSerializable, const prefix1.Json(discriminatorValue: "shoppingList")],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'name', 32773, 0, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(r'id', 32773, 0, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'users', 2129925, 0, const prefix1.JsonSerializable(), -1, 7, 8, const <int>[6, 1], const []),
        r.VariableMirrorImpl(
            r'modules', 2129925, 0, const prefix1.JsonSerializable(), -1, 9, 10, const <int>[6, 11], const []),
        r.VariableMirrorImpl(r'role', 32773, 1, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'nickname', 32773, 1, const prefix1.JsonSerializable(), -1, 12, 12, const <int>[], const []),
        r.VariableMirrorImpl(r'id', 32773, 2, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(r'name', 32773, 2, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'category', 32773, 2, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(r'hint', 32773, 2, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(r'id', 32773, 3, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(r'name', 32773, 3, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'entries', 2129925, 3, const prefix1.JsonSerializable(), -1, 13, 14, const <int>[15], const []),
        r.VariableMirrorImpl(r'note', 32773, 3, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'preparation', 32773, 4, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 0, 15),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 0, 16),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 1, 17),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 1, 18),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 2, 19),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 2, 20),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 3, 21),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 3, 22),
        r.MethodMirrorImpl(r'currentUser', 131075, 0, 1, 1, 1, const <int>[], const <int>[],
            const prefix1.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'', 0, 0, -1, 0, 0, const <int>[], const <int>[0, 1, 2, 3], const prefix1.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'==', 131074, -1, -1, 16, 16, const <int>[], const <int>[8], const prefix1.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, 6, 6, const <int>[], const <int>[],
            const prefix1.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, -1, -1, -1, -1, const <int>[], const <int>[9],
            const prefix1.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, 17, 17, const <int>[], const <int>[],
            const prefix1.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, 18, 18, const <int>[], const <int>[],
            const prefix1.JsonSerializable(), const []),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 4, 30),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 4, 31),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 5, 32),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 5, 33),
        r.MethodMirrorImpl(
            r'', 0, 1, -1, 1, 1, const <int>[], const <int>[10, 11], const prefix1.JsonSerializable(), const []),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 6, 35),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 6, 36),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 7, 37),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 7, 38),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 8, 39),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 8, 40),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 9, 41),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 9, 42),
        r.MethodMirrorImpl(r'', 0, 2, -1, 2, 2, const <int>[], const <int>[14, 15, 16, 17],
            const prefix1.JsonSerializable(), const []),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 10, 44),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 10, 45),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 11, 46),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 11, 47),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 12, 48),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 12, 49),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 13, 50),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 13, 51),
        r.MethodMirrorImpl(r'', 0, 3, -1, 3, 3, const <int>[], const <int>[22, 23, 24, 25],
            const prefix1.JsonSerializable(), const []),
        r.ImplicitGetterMirrorImpl(const prefix1.JsonSerializable(), 14, 53),
        r.ImplicitSetterMirrorImpl(const prefix1.JsonSerializable(), 14, 54),
        r.MethodMirrorImpl(r'', 0, 4, -1, 4, 4, const <int>[], const <int>[30, 31, 32, 33, 34],
            const prefix1.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'', 0, 5, -1, 5, 5, const <int>[], const <int>[36, 37, 38, 39], const prefix1.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'id', 32774, 24, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'name', 32774, 24, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'users', 2129926, 24, const prefix1.JsonSerializable(), -1, 7, 8, const <int>[6, 1], const [], null, null),
        r.ParameterMirrorImpl(r'modules', 2129926, 24, const prefix1.JsonSerializable(), -1, 9, 10, const <int>[6, 11],
            const [], null, null),
        r.ParameterMirrorImpl(
            r'_name', 32870, 16, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_id', 32870, 18, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'_users', 2130022, 20, const prefix1.JsonSerializable(), -1, 7, 8, const <int>[6, 1],
            const [], null, null),
        r.ParameterMirrorImpl(r'_modules', 2130022, 22, const prefix1.JsonSerializable(), -1, 9, 10, const <int>[6, 11],
            const [], null, null),
        r.ParameterMirrorImpl(
            r'other', 32774, 25, const prefix1.JsonSerializable(), -1, 19, 19, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'invocation', 32774, 27, const prefix1.JsonSerializable(), -1, 20, 20, const <int>[],
            const [], null, null),
        r.ParameterMirrorImpl(
            r'role', 32774, 34, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'nickname', 32774, 34, const prefix1.JsonSerializable(), -1, 12, 12, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_role', 32870, 31, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_nickname', 32870, 33, const prefix1.JsonSerializable(), -1, 12, 12, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'id', 32774, 43, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'name', 32774, 43, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'category', 32774, 43, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'hint', 32774, 43, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_id', 32870, 36, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_name', 32870, 38, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_category', 32870, 40, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_hint', 32870, 42, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'id', 32774, 52, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'name', 32774, 52, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'entries', 2129926, 52, const prefix1.JsonSerializable(), -1, 13, 14, const <int>[15],
            const [], null, null),
        r.ParameterMirrorImpl(
            r'note', 32774, 52, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_id', 32870, 45, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_name', 32870, 47, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'_entries', 2130022, 49, const prefix1.JsonSerializable(), -1, 13, 14, const <int>[15],
            const [], null, null),
        r.ParameterMirrorImpl(
            r'_note', 32870, 51, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'id', 32774, 55, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'name', 32774, 55, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'entries', 2129926, 55, const prefix1.JsonSerializable(), -1, 13, 14, const <int>[15],
            const [], null, null),
        r.ParameterMirrorImpl(
            r'preparation', 32774, 55, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'note', 32774, 55, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'_preparation', 32870, 54, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[],
            const [], null, null),
        r.ParameterMirrorImpl(
            r'id', 32774, 56, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'name', 32774, 56, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'entries', 2129926, 56, const prefix1.JsonSerializable(), -1, 13, 14, const <int>[15],
            const [], null, null),
        r.ParameterMirrorImpl(
            r'note', 32774, 56, const prefix1.JsonSerializable(), -1, 6, 6, const <int>[], const [], null, null)
      ],
      <Type>[
        prefix2.Trip,
        prefix2.TripUser,
        prefix8.Article,
        prefix8.ArticleList,
        prefix8.Recipe,
        prefix8.ShoppingList,
        String,
        const m.TypeValue<Map<String, prefix2.TripUser>>().type,
        Map,
        const m.TypeValue<Map<String, List<String>>>().type,
        Map,
        List,
        String,
        const m.TypeValue<List<prefix8.ArticleEntry>>().type,
        List,
        prefix8.ArticleEntry,
        bool,
        int,
        Type,
        Object,
        Invocation
      ],
      6,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'name': (dynamic instance) => instance.name,
        r'id': (dynamic instance) => instance.id,
        r'users': (dynamic instance) => instance.users,
        r'modules': (dynamic instance) => instance.modules,
        r'currentUser': (dynamic instance) => instance.currentUser,
        r'role': (dynamic instance) => instance.role,
        r'nickname': (dynamic instance) => instance.nickname,
        r'category': (dynamic instance) => instance.category,
        r'hint': (dynamic instance) => instance.hint,
        r'entries': (dynamic instance) => instance.entries,
        r'note': (dynamic instance) => instance.note,
        r'preparation': (dynamic instance) => instance.preparation
      },
      {
        r'name=': (dynamic instance, value) => instance.name = value,
        r'id=': (dynamic instance, value) => instance.id = value,
        r'users=': (dynamic instance, value) => instance.users = value,
        r'modules=': (dynamic instance, value) => instance.modules = value,
        r'role=': (dynamic instance, value) => instance.role = value,
        r'nickname=': (dynamic instance, value) => instance.nickname = value,
        r'category=': (dynamic instance, value) => instance.category = value,
        r'hint=': (dynamic instance, value) => instance.hint = value,
        r'entries=': (dynamic instance, value) => instance.entries = value,
        r'note=': (dynamic instance, value) => instance.note = value,
        r'preparation=': (dynamic instance, value) => instance.preparation = value
      },
      null,
      []),
  const prefix0.Module(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'TheButtonModule',
            r'.TheButtonModule',
            7,
            0,
            const prefix0.Module(),
            const <int>[0, 5, 8],
            const <int>[9, 10, 11, 12, 13, 5, 6, 7],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (moduleData) => b ? prefix3.TheButtonModule(moduleData) : null},
            -1,
            -1,
            const <int>[-1],
            const [const prefix0.Module()],
            null),
        r.NonGenericClassMirrorImpl(
            r'WelcomeModule',
            r'.WelcomeModule',
            7,
            1,
            const prefix0.Module(),
            const <int>[1, 14, 15, 16, 17, 18, 19, 22],
            const <int>[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (moduleData) => b ? prefix4.WelcomeModule(moduleData) : null},
            -1,
            -1,
            const <int>[-1],
            const [const prefix0.Module()],
            null),
        r.NonGenericClassMirrorImpl(
            r'ProfileModule',
            r'.ProfileModule',
            7,
            2,
            const prefix0.Module(),
            const <int>[2, 23, 26],
            const <int>[9, 10, 11, 12, 13, 23, 24, 25],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (moduleData) => b ? prefix5.ProfileModule(moduleData) : null},
            -1,
            -1,
            const <int>[-1],
            const [const prefix0.Module()],
            null),
        r.NonGenericClassMirrorImpl(
            r'SupplyModule',
            r'.SupplyModule',
            7,
            3,
            const prefix0.Module(),
            const <int>[3, 27, 28, 31],
            const <int>[9, 10, 11, 12, 13, 27, 28, 29, 30],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (moduleData) => b ? prefix6.SupplyModule(moduleData) : null},
            -1,
            -1,
            const <int>[-1],
            const [const prefix0.Module()],
            null),
        r.NonGenericClassMirrorImpl(
            r'UsersModule',
            r'.UsersModule',
            7,
            4,
            const prefix0.Module(),
            const <int>[4, 32, 35],
            const <int>[9, 10, 11, 12, 13, 32, 33, 34],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (moduleData) => b ? prefix7.UsersModule(moduleData) : null},
            -1,
            -1,
            const <int>[-1],
            const [const prefix0.Module()],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'moduleData', 32773, 0, const prefix0.Module(), -1, 5, 5, null, const []),
        r.VariableMirrorImpl(r'moduleData', 32773, 1, const prefix0.Module(), -1, 5, 5, null, const []),
        r.VariableMirrorImpl(r'moduleData', 32773, 2, const prefix0.Module(), -1, 5, 5, null, const []),
        r.VariableMirrorImpl(r'moduleData', 32773, 3, const prefix0.Module(), -1, 5, 5, null, const []),
        r.VariableMirrorImpl(r'moduleData', 32773, 4, const prefix0.Module(), -1, 5, 5, null, const []),
        r.MethodMirrorImpl(r'getButtonCard', 131074, 0, -1, 6, 6, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "thebutton")]),
        r.ImplicitGetterMirrorImpl(const prefix0.Module(), 0, 6),
        r.ImplicitSetterMirrorImpl(const prefix0.Module(), 0, 7),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, null, const <int>[0], const prefix0.Module(), const []),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, 7, 7, null, const <int>[2], const prefix0.Module(), const []),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, 8, 8, null, const <int>[], const prefix0.Module(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod', 65538, -1, -1, -1, -1, null, const <int>[3], const prefix0.Module(), const []),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, 9, 9, null, const <int>[], const prefix0.Module(), const []),
        r.MethodMirrorImpl(
            r'runtimeType', 131075, -1, -1, 10, 10, null, const <int>[], const prefix0.Module(), const []),
        r.MethodMirrorImpl(r'getAction1', 131074, 1, -1, 11, 11, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "action1")]),
        r.MethodMirrorImpl(r'getAction2', 131074, 1, -1, 11, 11, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "action2")]),
        r.MethodMirrorImpl(r'getAction3', 131074, 1, -1, 11, 11, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "action3")]),
        r.MethodMirrorImpl(r'getWelcomeBanner', 131074, 1, -1, 6, 6, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "halloid")]),
        r.MethodMirrorImpl(r'getWelcomeBanner2', 131074, 1, -1, 6, 6, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "banner2")]),
        r.MethodMirrorImpl(r'getWelcomeBanner3', 131074, 1, -1, 6, 6, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "test123")]),
        r.ImplicitGetterMirrorImpl(const prefix0.Module(), 1, 20),
        r.ImplicitSetterMirrorImpl(const prefix0.Module(), 1, 21),
        r.MethodMirrorImpl(r'', 0, 1, -1, 1, 1, null, const <int>[4], const prefix0.Module(), const []),
        r.MethodMirrorImpl(r'getProfileCard', 131074, 2, -1, 6, 6, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "profile")]),
        r.ImplicitGetterMirrorImpl(const prefix0.Module(), 2, 24),
        r.ImplicitSetterMirrorImpl(const prefix0.Module(), 2, 25),
        r.MethodMirrorImpl(r'', 0, 2, -1, 2, 2, null, const <int>[6], const prefix0.Module(), const []),
        r.MethodMirrorImpl(r'getCookingCard', 131074, 3, -1, 6, 6, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "cooking")]),
        r.MethodMirrorImpl(r'getShoppingCard', 131074, 3, -1, 6, 6, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "shopping")]),
        r.ImplicitGetterMirrorImpl(const prefix0.Module(), 3, 29),
        r.ImplicitSetterMirrorImpl(const prefix0.Module(), 3, 30),
        r.MethodMirrorImpl(r'', 0, 3, -1, 3, 3, null, const <int>[8], const prefix0.Module(), const []),
        r.MethodMirrorImpl(r'getUsers', 131074, 4, -1, 6, 6, null, const <int>[], const prefix0.Module(),
            const [const prefix0.ModuleItem(id: "users")]),
        r.ImplicitGetterMirrorImpl(const prefix0.Module(), 4, 33),
        r.ImplicitSetterMirrorImpl(const prefix0.Module(), 4, 34),
        r.MethodMirrorImpl(r'', 0, 4, -1, 4, 4, null, const <int>[10], const prefix0.Module(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'moduleData', 32774, 8, const prefix0.Module(), -1, 5, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'_moduleData', 32870, 7, const prefix0.Module(), -1, 5, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'other', 32774, 9, const prefix0.Module(), -1, 12, 12, null, const [], null, null),
        r.ParameterMirrorImpl(r'invocation', 32774, 11, const prefix0.Module(), -1, 13, 13, null, const [], null, null),
        r.ParameterMirrorImpl(r'moduleData', 32774, 22, const prefix0.Module(), -1, 5, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'_moduleData', 32870, 21, const prefix0.Module(), -1, 5, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'moduleData', 32774, 26, const prefix0.Module(), -1, 5, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'_moduleData', 32870, 25, const prefix0.Module(), -1, 5, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'moduleData', 32774, 31, const prefix0.Module(), -1, 5, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'_moduleData', 32870, 30, const prefix0.Module(), -1, 5, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'moduleData', 32774, 35, const prefix0.Module(), -1, 5, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'_moduleData', 32870, 34, const prefix0.Module(), -1, 5, 5, null, const [], null, null)
      ],
      <Type>[
        prefix3.TheButtonModule,
        prefix4.WelcomeModule,
        prefix5.ProfileModule,
        prefix6.SupplyModule,
        prefix7.UsersModule,
        prefix0.ModuleData,
        prefix9.ContentSegment,
        bool,
        String,
        int,
        Type,
        prefix9.QuickAction,
        Object,
        Invocation
      ],
      5,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'getButtonCard': (dynamic instance) => instance.getButtonCard,
        r'moduleData': (dynamic instance) => instance.moduleData,
        r'getAction1': (dynamic instance) => instance.getAction1,
        r'getAction2': (dynamic instance) => instance.getAction2,
        r'getAction3': (dynamic instance) => instance.getAction3,
        r'getWelcomeBanner': (dynamic instance) => instance.getWelcomeBanner,
        r'getWelcomeBanner2': (dynamic instance) => instance.getWelcomeBanner2,
        r'getWelcomeBanner3': (dynamic instance) => instance.getWelcomeBanner3,
        r'getProfileCard': (dynamic instance) => instance.getProfileCard,
        r'getCookingCard': (dynamic instance) => instance.getCookingCard,
        r'getShoppingCard': (dynamic instance) => instance.getShoppingCard,
        r'getUsers': (dynamic instance) => instance.getUsers
      },
      {r'moduleData=': (dynamic instance, value) => instance.moduleData = value},
      null,
      [])
};

final _memberSymbolMap = null;

void _initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}

final mainAdapter = JsonMapperAdapter(title: 'mainAdapter', url: 'package:jufa/main.dart', valueDecorators: {
  typeOf<List<x0.Trip>>(): (value) => value.cast<x0.Trip>(),
  typeOf<Set<x0.Trip>>(): (value) => value.cast<x0.Trip>(),
  typeOf<List<x0.TripUser>>(): (value) => value.cast<x0.TripUser>(),
  typeOf<Set<x0.TripUser>>(): (value) => value.cast<x0.TripUser>(),
  typeOf<List<x1.Article>>(): (value) => value.cast<x1.Article>(),
  typeOf<Set<x1.Article>>(): (value) => value.cast<x1.Article>(),
  typeOf<List<x1.ArticleList>>(): (value) => value.cast<x1.ArticleList>(),
  typeOf<Set<x1.ArticleList>>(): (value) => value.cast<x1.ArticleList>(),
  typeOf<List<x1.Recipe>>(): (value) => value.cast<x1.Recipe>(),
  typeOf<Set<x1.Recipe>>(): (value) => value.cast<x1.Recipe>(),
  typeOf<List<x1.ShoppingList>>(): (value) => value.cast<x1.ShoppingList>(),
  typeOf<Set<x1.ShoppingList>>(): (value) => value.cast<x1.ShoppingList>()
}, enumValues: {});

Future<JsonMapper> initializeJsonMapperAsync({Iterable<JsonMapperAdapter> adapters = const []}) =>
    Future(() => initializeJsonMapper(adapters: adapters));

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const []}) {
  _initializeReflectable();
  [...adapters, mainAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}
