# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  desc "Upload a new version to the Google Play"
  lane :upload do
    upload_to_play_store(aab: "../build/app/outputs/bundle/release/app-release.aab", track: 'internal', release_status: "draft")
  end

  desc "Upload to VS App Center"
  lane :upload_app_center do
    appcenter_upload(
      owner_name: "schultek",
      owner_type: "user",
      app_name: "Jufa",
      destinations: "Testers",
      file: "../build/app/outputs/flutter-apk/app-release.apk",
      notify_testers: true
    )
  end

end
