include: package:lint/analysis_options.yaml

analyzer:
  exclude: [lib/generated**, lib/main.reflectable.dart]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

linter:
  rules:
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    constant_identifier_names: false
    prefer_relative_imports: true
    unnecessary_final: true
    prefer_final_locals: false
    prefer_final_in_for_each: false
    avoid_print: false # TODO remove in production